### ISSUE TITLE
Show a rough idea of the card count in each stack

### ISSUE THREAD

**Issue by tomassedovic** [HereBeMike/Gridcannon#2]
I was looking to see if someone made this on a computer already and it's brilliant, thanks!

One thing that makes this version harder from a physical card game is that (unless you remember), you've got no idea if a given stack has say 1 card or 10. With the physical cards you can get at least a rough idea.

Showing the whole number might give too much information, but something like HoMaM's style `a few`, `several` & `lots` might help when you need to bring a stack back and want to minimise the amount of times you do it.

**Comment by HereBeMike** [comment]
Good point. Thanks for the feedback. I'll get onto that in the next week or so!

**Comment by tomassedovic** [comment]
Thanks! \o/

**Comment by HereBeMike** [comment]
I just applied a fix for this, but I'm tired. Hopefully I didn't break anything! :)
